name: Unittest
on:
  push:
    branches: 
      - main
      - develop

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest

    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.filter.outputs.src }}
      test: ${{ steps.filter.outputs.test }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            src:
              - 'cnlp/**'
            test:
              - 'tests/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' ||  needs.changes.outputs.test }}
    name: Run python unittests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: unittests
        run: |
            python -m pip install -e .
            python -m pip install -r requirements/requirements.txt
            python -m pip install -r requirements/requirements-test.txt
            python -m unittest discover -v -s tests/ -t .
